#!/bin/sh
# Убираем бридж
uci -q delete network.@device[0]

# lan = eth0
uci set network.lan.device='eth0'

if [ -e /sys/class/net/eth1 ]; then
    # Две сетевухи: lan=static, wan=dhcp
    uci set network.lan.proto='static'
    uci set network.lan.ipaddr='192.168.1.1/24'

    uci -q delete network.wan
    uci set network.wan=interface
    uci set network.wan.device='eth1'
    uci set network.wan.proto='dhcp'
else
    # Одна сетевуха: lan=dhcp
    uci set network.lan.proto='dhcp'
    uci -q delete network.lan.ipaddr
fi

uci commit network
