#!/bin/sh
# Configure WAN interface on USB Ethernet (eth1)
uci -q delete network.wan
uci set network.wan=interface
uci set network.wan.device='eth1'
uci set network.wan.proto='dhcp'
uci commit network

# Configure firewall zone for WAN
uci -q delete firewall.wan_zone
uci set firewall.wan_zone=zone
uci set firewall.wan_zone.name='wan'
uci set firewall.wan_zone.network='wan'
uci set firewall.wan_zone.input='REJECT'
uci set firewall.wan_zone.output='ACCEPT'
uci set firewall.wan_zone.forward='REJECT'
uci set firewall.wan_zone.masq='1'
uci set firewall.wan_zone.mtu_fix='1'
uci commit firewall
