#!/bin/sh
uci -q delete mbusd.@mbusd[0]
uci -q batch << EOF
add mbusd mbusd
set mbusd.@mbusd[0].enabled=0
set mbusd.@mbusd[0].port=502
set mbusd.@mbusd[0].loglevel=2
set mbusd.@mbusd[0].device=/dev/ttyS1
set mbusd.@mbusd[0].speed=115200
set mbusd.@mbusd[0].databits=8
set mbusd.@mbusd[0].parity=N
set mbusd.@mbusd[0].stopbits=1
set mbusd.@mbusd[0].rts=0
commit mbusd
EOF
/etc/init.d/mbusd disable
exit 0
