#!/bin/sh
CID=$(cat /sys/class/block/mmcblk0/device/cid)
[ -z "$CID" ] && exit 0
MAC=$(echo "$CID" | md5sum | sed 's/\(..\)\(..\)\(..\)\(..\)\(..\)\(..\).*/02:\1:\2:\3:\4:\5/')
WAN_MAC=$(echo "${CID}wan" | md5sum | sed 's/\(..\)\(..\)\(..\)\(..\)\(..\)\(..\).*/02:\1:\2:\3:\4:\5/')
uci set network.lan.macaddr="$MAC"
uci set network.wan=interface
uci set network.wan.macaddr="$WAN_MAC"
uci commit network
